### ISSUE TITLE
Mobile optimization

### ISSUE THREAD

**Issue by ultraindv** [Vivaan-d/PreciseTools#3]
<img src="https://tahj-s.github.io/Precise-Tools-Pack/Precise%20Tools%20logo%20Transparent.png" width="200">

# Mobile Optimisation
### Mobile optimisation is a key thing about the website that isn't optimised for mobile
It will be something to be fixed in the future

**Comment by Vivaan-d** [comment]
i dont care about mobile

**Comment by Vivaan-d** [comment]
yes
