### ISSUE TITLE
Putting A specific button to good use

### ISSUE THREAD

**Issue by ultraindv** [Vivaan-d/PreciseTools#5]
<div align="center">
<img src="https://precisetools-pack.netlify.app/Precise%20Tools%20logo%20Transparent.png" alt="PreciseTools Logo" width="350">
</div>

# Issue 5! (kinda)
Today it has come to matters to use the "MORE Insane Calculators!" button to use and make a page showing all Tools

# Coming in this Commit Wave
- [x] PWA Update 1
- [x] Bug Fixes
- [x] Tool Nav

**Comment by Vivaan-d** [comment]
shut just say that it isnt functional

**Comment by ultraindv** [comment]
Oooh plot twist
